Traceback (most recent call last):
  File "C:\Users\Sean\anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\Sean\anaconda3\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\Sean\anaconda3\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\Sean\anaconda3\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\Sean\anaconda3\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Users\Sean\anaconda3\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\Sean\anaconda3\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\Sean\anaconda3\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
fig, ax = plt.subplots(figsize=[8,6])
ax.axis(False) #since this is an image, we don't need the x & y axis

# we use matplotlib.imread to read our image file and imshow to display it.
path=r'C:\Users\sgc\Google Drive\Teaching\2114 & 3114 Math I & II\3114 Python\images'
filename ='crystallization kinetics poly testing 48 2015 p 125.png'
img = mpimg.imread(os.path.join(path, filename)) #matplotlib
ax=plt.imshow(img)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mFileNotFoundError[0m                         Traceback (most recent call last)
Input [1;32mIn [2][0m, in [0;36m<cell line: 7>[1;34m()[0m
[0;32m      5[0m path[38;5;241m=[39m[38;5;124mr[39m[38;5;124m'[39m[38;5;124mC:[39m[38;5;124m\[39m[38;5;124mUsers[39m[38;5;124m\[39m[38;5;124msgc[39m[38;5;124m\[39m[38;5;124mGoogle Drive[39m[38;5;124m\[39m[38;5;124mTeaching[39m[38;5;124m\[39m[38;5;124m2114 & 3114 Math I & II[39m[38;5;124m\[39m[38;5;124m3114 Python[39m[38;5;124m\[39m[38;5;124mimages[39m[38;5;124m'[39m
[0;32m      6[0m filename [38;5;241m=[39m[38;5;124m'[39m[38;5;124mcrystallization kinetics poly testing 48 2015 p 125.png[39m[38;5;124m'[39m
[1;32m----> 7[0m img [38;5;241m=[39m [43mmpimg[49m[38;5;241;43m.[39;49m[43mimread[49m[43m([49m[43mos[49m[38;5;241;43m.[39;49m[43mpath[49m[38;5;241;43m.[39;49m[43mjoin[49m[43m([49m[43mpath[49m[43m,[49m[43m [49m[43mfilename[49m[43m)[49m[43m)[49m [38;5;66;03m#matplotlib[39;00m
[0;32m      8[0m ax[38;5;241m=[39mplt[38;5;241m.[39mimshow(img)

File [1;32m~\anaconda3\lib\site-packages\matplotlib\image.py:1560[0m, in [0;36mimread[1;34m(fname, format)[0m
[0;32m   1558[0m                 response [38;5;241m=[39m io[38;5;241m.[39mBytesIO(response[38;5;241m.[39mread())
[0;32m   1559[0m             [38;5;28;01mreturn[39;00m imread(response, [38;5;28mformat[39m[38;5;241m=[39mext)
[1;32m-> 1560[0m [38;5;28;01mwith[39;00m [43mimg_open[49m[43m([49m[43mfname[49m[43m)[49m [38;5;28;01mas[39;00m image:
[0;32m   1561[0m     [38;5;28;01mreturn[39;00m (_pil_png_to_float_array(image)
[0;32m   1562[0m             [38;5;28;01mif[39;00m [38;5;28misinstance[39m(image, PIL[38;5;241m.[39mPngImagePlugin[38;5;241m.[39mPngImageFile) [38;5;28;01melse[39;00m
[0;32m   1563[0m             pil_to_array(image))

File [1;32m~\anaconda3\lib\site-packages\PIL\ImageFile.py:100[0m, in [0;36mImageFile.__init__[1;34m(self, fp, filename)[0m
[0;32m     96[0m [38;5;28mself[39m[38;5;241m.[39mdecodermaxblock [38;5;241m=[39m MAXBLOCK
[0;32m     98[0m [38;5;28;01mif[39;00m isPath(fp):
[0;32m     99[0m     [38;5;66;03m# filename[39;00m
[1;32m--> 100[0m     [38;5;28mself[39m[38;5;241m.[39mfp [38;5;241m=[39m [38;5;28;43mopen[39;49m[43m([49m[43mfp[49m[43m,[49m[43m [49m[38;5;124;43m"[39;49m[38;5;124;43mrb[39;49m[38;5;124;43m"[39;49m[43m)[49m
[0;32m    101[0m     [38;5;28mself[39m[38;5;241m.[39mfilename [38;5;241m=[39m fp
[0;32m    102[0m     [38;5;28mself[39m[38;5;241m.[39m_exclusive_fp [38;5;241m=[39m [38;5;28;01mTrue[39;00m

[1;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'C:\\Users\\sgc\\Google Drive\\Teaching\\2114 & 3114 Math I & II\\3114 Python\\images\\crystallization kinetics poly testing 48 2015 p 125.png'
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\sgc\\Google Drive\\Teaching\\2114 & 3114 Math I & II\\3114 Python\\images\\crystallization kinetics poly testing 48 2015 p 125.png'

